In [1]:
import numpy as np

In [2]:
N_s = 8
n_s = 8
k =  3 * np.pi / 8
sigma = 3/2
r = [-1, 0, 1, 2, 3, 4, -3, -2]
# r = np.roll(np.array(r), 4)

In [3]:
np.arange(-3, 5, 1)

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [4]:
GWP_coeffs = []
for i in range(n_s):
    coeff = np.exp(-1j * k * i) * np.exp(-r[i]**2 / sigma**2)
    GWP_coeffs.append(coeff)
GWP_coeffs = np.array(GWP_coeffs)
GWP_coeffs /= np.linalg.norm(GWP_coeffs)

betas = []
for i in range(n_s):
    betas.append(-np.angle(GWP_coeffs[i]))
betas = np.array(betas)
p = np.diag(np.exp(1j * betas))

In [5]:
def Giv_Mat(theta, s):
    mat = np.identity(n_s, dtype=float)
    mat[s-1, s-1] = np.cos(theta)
    mat[s-1, s] = -np.sin(theta)
    mat[s, s-1] = np.sin(theta)
    mat[s, s] = np.cos(theta)
    return mat

In [6]:
GWP_coeffs = p @ GWP_coeffs
print(GWP_coeffs)
thetas = []
for i in range(n_s-1):
    j = n_s - 1 - i
    theta = np.arctan(-np.abs(GWP_coeffs[j]) / np.abs(GWP_coeffs[j-1]))
    thetas.append(theta)
    GWP_coeffs = Giv_Mat(theta, j) @ GWP_coeffs
print(GWP_coeffs)

[4.67625480e-01+0.00000000e+00j 7.29319687e-01+0.00000000e+00j
 4.67625480e-01+0.00000000e+00j 1.23264738e-01+2.77555756e-17j
 1.33579560e-02+3.05693549e-19j 5.95115992e-04+0.00000000e+00j
 1.33579560e-02+0.00000000e+00j 1.23264738e-01+6.93889390e-18j]
[ 1.00000000e+00+4.28068814e-18j  0.00000000e+00+2.26462087e-18j
  0.00000000e+00+7.07213153e-18j -2.77555756e-17+2.28588941e-17j
  0.00000000e+00-1.48952207e-17j  8.67361738e-18+4.34998134e-19j
 -9.86623977e-18+3.31113989e-20j  3.46944695e-18+7.47577393e-19j]


In [7]:
betas

array([-0.        ,  1.17809725,  2.35619449, -2.74889357, -1.57079633,
       -0.39269908,  0.78539816,  1.96349541])

In [8]:
thetas

[np.float64(-1.4628495506187855),
 np.float64(-1.565996515216672),
 np.float64(-1.4634742646356191),
 np.float64(-0.7912076450496149),
 np.float64(-0.35874202677184114),
 np.float64(-0.6004336402695971),
 np.float64(-1.0841937949333018)]

In [9]:
GWP_coeffs

array([ 1.00000000e+00+4.28068814e-18j,  0.00000000e+00+2.26462087e-18j,
        0.00000000e+00+7.07213153e-18j, -2.77555756e-17+2.28588941e-17j,
        0.00000000e+00-1.48952207e-17j,  8.67361738e-18+4.34998134e-19j,
       -9.86623977e-18+3.31113989e-20j,  3.46944695e-18+7.47577393e-19j])